# Generated by Django 5.2.7 on 2025-10-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autogas', '0001_initial'),
        ('filling_station', '0001_initial'),
        ('railway_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Контрагент')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email адрес')),
                ('active', models.BooleanField(default=True, verbose_name='Включен в рассылку')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Получатель почты',
                'verbose_name_plural': 'Получатели почты',
            },
        ),
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Путь сохранения файла',
                'verbose_name_plural': 'Путь сохранения файла',
            },
        ),
        migrations.CreateModel(
            name='BalloonTtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер ТТН')),
                ('contract', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата формирования накладной')),
                ('loading_batch', models.ForeignKey(blank=True, limit_choices_to={'batch_type': 'l'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_ttn_loading', to='filling_station.balloonsbatch', verbose_name='Партия приёмки')),
                ('unloading_batch', models.ForeignKey(blank=True, limit_choices_to={'batch_type': 'u'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_ttn_unloading', to='filling_station.balloonsbatch', verbose_name='Партия отгрузки')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_city', to='ttn.city', verbose_name='Город')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_carrier', to='ttn.contractor', verbose_name='Перевозчик')),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_consignee', to='ttn.contractor', verbose_name='Грузополучатель')),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_shipper', to='ttn.contractor', verbose_name='Грузоотправитель')),
            ],
            options={
                'verbose_name': 'Баллоны',
                'verbose_name_plural': 'Баллоны',
                'ordering': ['-id', '-date'],
            },
        ),
        migrations.CreateModel(
            name='AutoTtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер ТТН')),
                ('contract', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('total_gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество газа')),
                ('source_gas_amount', models.CharField(blank=True, max_length=20, null=True, verbose_name='Источник веса для ТТН')),
                ('gas_type', models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата формирования накладной')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_batch_for_ttn', to='autogas.autogasbatch', verbose_name='Партия')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tank_city', to='ttn.city', verbose_name='Город')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tank_carrier', to='ttn.contractor', verbose_name='Перевозчик')),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tank_consignee', to='ttn.contractor', verbose_name='Грузополучатель')),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tank_shipper', to='ttn.contractor', verbose_name='Грузоотправитель')),
            ],
            options={
                'verbose_name': 'Автоцистерны',
                'verbose_name_plural': 'Автоцистерны',
                'ordering': ['-id', '-date'],
            },
        ),
        migrations.CreateModel(
            name='RailwayTtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер ТТН')),
                ('railway_ttn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ж/д накладной')),
                ('contract', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('total_gas_amount_by_scales', models.FloatField(blank=True, null=True, verbose_name='Количество газа по весам')),
                ('total_gas_amount_by_ttn', models.FloatField(blank=True, null=True, verbose_name='Количество газа по ТТН')),
                ('gas_type', models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата формирования накладной')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='railway_tank_carrier', to='ttn.contractor', verbose_name='Перевозчик')),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='railway_tank_consignee', to='ttn.contractor', verbose_name='Грузополучатель')),
                ('railway_tank_list', models.ManyToManyField(blank=True, to='railway_service.railwaytank', verbose_name='Список жд цистерн')),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='railway_tank_shipper', to='ttn.contractor', verbose_name='Грузоотправитель')),
            ],
            options={
                'verbose_name': 'Железнодорожная ТТН',
                'verbose_name_plural': 'Железнодорожные ТТН',
                'ordering': ['-id', '-date'],
            },
        ),
    ]
