# Generated by Django 5.1.4 on 2025-05-01 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filling_station', '0064_alter_autottn_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Контрагент')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='AutoTtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер ТТН')),
                ('contract', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('total_gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество газа')),
                ('source_gas_amount', models.CharField(blank=True, max_length=20, null=True, verbose_name='Источник веса для ТТН')),
                ('gas_type', models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата формирования накладной')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_batch_for_ttn', to='filling_station.autogasbatch', verbose_name='Партия')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tank_carrier', to='ttn.contractor', verbose_name='Перевозчик')),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tank_consignee', to='ttn.contractor', verbose_name='Грузополучатель')),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tank_shipper', to='ttn.contractor', verbose_name='Грузоотправитель')),
            ],
            options={
                'verbose_name': 'ТТН на автоцистерны',
                'verbose_name_plural': 'ТТН на автоцистерны',
                'ordering': ['-id', '-date'],
            },
        ),
        migrations.CreateModel(
            name='RailwayTtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер ТТН')),
                ('railway_ttn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ж/д накладной')),
                ('contract', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('total_gas_amount_by_scales', models.FloatField(blank=True, null=True, verbose_name='Количество газа по весам')),
                ('total_gas_amount_by_ttn', models.FloatField(blank=True, null=True, verbose_name='Количество газа по ТТН')),
                ('gas_type', models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата формирования накладной')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='railway_tank_carrier', to='ttn.contractor', verbose_name='Перевозчик')),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='railway_tank_consignee', to='ttn.contractor', verbose_name='Грузополучатель')),
                ('railway_tank_list', models.ManyToManyField(blank=True, to='filling_station.railwaytank', verbose_name='Список жд цистерн')),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='railway_tank_shipper', to='ttn.contractor', verbose_name='Грузоотправитель')),
            ],
            options={
                'verbose_name': 'Железнодорожная ТТН',
                'verbose_name_plural': 'Железнодорожные ТТН',
                'ordering': ['-id', '-date'],
            },
        ),
        migrations.CreateModel(
            name='TTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер ТТН')),
                ('contract', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата формирования накладной')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_carrier', to='ttn.contractor', verbose_name='Перевозчик')),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_consignee', to='ttn.contractor', verbose_name='Грузополучатель')),
                ('loading_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttn_loading', to='filling_station.balloonsloadingbatch', verbose_name='Партия приёмки')),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_shipper', to='ttn.contractor', verbose_name='Грузоотправитель')),
                ('unloading_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttn_unloading', to='filling_station.balloonsunloadingbatch', verbose_name='Партия отгрузки')),
            ],
            options={
                'verbose_name': 'ТТН на баллоны',
                'verbose_name_plural': 'ТТН на баллоны',
                'ordering': ['-id', '-date'],
            },
        ),
    ]
