# Generated by Django 5.2.7 on 2025-12-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiriadaTtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttn_id', models.IntegerField(unique=True, verbose_name='ID ТТН в Мириаде')),
                ('name', models.CharField(max_length=100, verbose_name='Номер ТТН')),
                ('auto', models.CharField(max_length=50, verbose_name='Номер автомобиля')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата ТТН')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'ТТН из Мириады',
                'verbose_name_plural': 'ТТН из Мириады',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
