# Generated by Django 5.1.4 on 2025-05-02 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autottn',
            options={'ordering': ['-date'], 'verbose_name': 'Автоцистерны', 'verbose_name_plural': 'Автоцистерны'},
        ),
        migrations.AlterModelOptions(
            name='railwayttn',
            options={'ordering': ['-date'], 'verbose_name': 'Железнодорожная ТТН', 'verbose_name_plural': 'Железнодорожные ТТН'},
        ),
        migrations.AlterModelOptions(
            name='ttn',
            options={'ordering': ['-date'], 'verbose_name': 'Баллоны', 'verbose_name_plural': 'Баллоны'},
        ),
        migrations.AddField(
            model_name='autottn',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tank_city', to='ttn.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='ttn',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_city', to='ttn.city', verbose_name='Город'),
        ),
    ]
