# Generated by Django 5.2.4 on 2025-12-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0002_miriadattn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miriadattn',
            options={'ordering': ['-created_at'], 'verbose_name': 'ТТН из Мириады', 'verbose_name_plural': 'ТТН из Мириады'},
        ),
        migrations.RemoveField(
            model_name='miriadattn',
            name='date',
        ),
    ]
