# Generated by Django 5.1.4 on 2025-05-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0066_delete_filepath'),
        ('ttn', '0002_alter_autottn_options_alter_railwayttn_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Путь сохранения файла',
                'verbose_name_plural': 'Путь сохранения файла',
            },
        ),
        migrations.AlterModelOptions(
            name='autottn',
            options={'ordering': ['-id', '-date'], 'verbose_name': 'Автоцистерны', 'verbose_name_plural': 'Автоцистерны'},
        ),
        migrations.AlterModelOptions(
            name='railwayttn',
            options={'ordering': ['-id', '-date'], 'verbose_name': 'Железнодорожная ТТН', 'verbose_name_plural': 'Железнодорожные ТТН'},
        ),
        migrations.CreateModel(
            name='BalloonTtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер ТТН')),
                ('contract', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата формирования накладной')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_carrier', to='ttn.contractor', verbose_name='Перевозчик')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_city', to='ttn.city', verbose_name='Город')),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_consignee', to='ttn.contractor', verbose_name='Грузополучатель')),
                ('loading_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_ttn_loading', to='filling_station.balloonsloadingbatch', verbose_name='Партия приёмки')),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_shipper', to='ttn.contractor', verbose_name='Грузоотправитель')),
                ('unloading_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_ttn_unloading', to='filling_station.balloonsunloadingbatch', verbose_name='Партия отгрузки')),
            ],
            options={
                'verbose_name': 'Баллоны',
                'verbose_name_plural': 'Баллоны',
                'ordering': ['-id', '-date'],
            },
        ),
        migrations.DeleteModel(
            name='TTN',
        ),
    ]
