# Generated by Django 5.1.4 on 2025-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_service', '0001_initial'),
        ('ttn', '0003_filepath_alter_autottn_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwayttn',
            name='railway_tank_list',
            field=models.ManyToManyField(blank=True, to='railway_service.railwaytank', verbose_name='Список жд цистерн'),
        ),
    ]
