# Generated by Django 5.2.4 on 2025-12-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0003_alter_miriadattn_options_remove_miriadattn_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='miriadattn',
            name='date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дата ТТН'),
        ),
    ]
