# Generated by Django 5.2.1 on 2025-07-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0004_alter_railwayttn_railway_tank_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autottn',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата формирования накладной'),
        ),
        migrations.AlterField(
            model_name='balloonttn',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата формирования накладной'),
        ),
        migrations.AlterField(
            model_name='railwayttn',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата формирования накладной'),
        ),
    ]
