# Generated by Django 5.2.4 on 2025-12-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0004_miriadattn_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miriadattn',
            options={'ordering': ['-updated_at'], 'verbose_name': 'ТТН из Мириады', 'verbose_name_plural': 'ТТН из Мириады'},
        ),
        migrations.RemoveField(
            model_name='miriadattn',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='miriadattn',
            name='date',
        ),
    ]
