# Generated by Django 5.2.4 on 2025-12-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0005_alter_miriadattn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miriadattn',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ТТН'),
        ),
    ]
