# Generated by Django 5.2.1 on 2025-07-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autogas', '0001_initial'),
        ('ttn', '0005_alter_autottn_date_alter_balloonttn_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autottn',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_batch_for_ttn', to='autogas.autogasbatch', verbose_name='Партия'),
        ),
    ]
