# Generated by Django 5.2.1 on 2025-07-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0006_alter_autottn_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autottn',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата формирования накладной'),
        ),
    ]
