# Generated by Django 5.2.4 on 2026-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0006_miriadattn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autottn',
            name='gas_type',
            field=models.CharField(choices=[('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа'),
        ),
        migrations.AlterField(
            model_name='railwayttn',
            name='gas_type',
            field=models.CharField(choices=[('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа'),
        ),
    ]
