# Generated by Django 5.2.1 on 2025-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0007_alter_autottn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloonttn',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата формирования накладной'),
        ),
        migrations.AlterField(
            model_name='railwayttn',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата формирования накладной'),
        ),
    ]
