# Generated by Django 5.2.4 on 2025-08-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0008_alter_balloonttn_date_alter_railwayttn_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email адрес')),
                ('active', models.BooleanField(default=True, verbose_name='Включен в рассылку')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Получатель почты',
                'verbose_name_plural': 'Получатели почты',
            },
        ),
    ]
