# Generated by Django 5.2.4 on 2025-10-21 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0078_remove_balloonsloadingbatch_balloon_list_and_more'),
        ('ttn', '0011_clear_balloon_batch_references_before_alter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloonttn',
            name='loading_batch',
            field=models.ForeignKey(blank=True, limit_choices_to={'batch_type': 'l'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_ttn_loading', to='filling_station.balloonsbatch', verbose_name='Партия приёмки'),
        ),
        migrations.AlterField(
            model_name='balloonttn',
            name='unloading_batch',
            field=models.ForeignKey(blank=True, limit_choices_to={'batch_type': 'u'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_ttn_unloading', to='filling_station.balloonsbatch', verbose_name='Партия отгрузки'),
        ),
    ]
