# Generated by Django 5.2.4 on 2025-10-21 13:22

from django.db import migrations


def restore_balloon_batch_references(apps, schema_editor):
    """
    Восстанавливает ссылки на партии баллонов после изменения внешних ключей
    """
    BalloonTtn = apps.get_model('ttn', 'BalloonTtn')
    BalloonsBatch = apps.get_model('filling_station', 'BalloonsBatch')
    
    # Получаем все записи BalloonTtn
    balloon_ttns = BalloonTtn.objects.all()
    
    for ttn in balloon_ttns:
        # Восстанавливаем loading_batch если есть соответствующие записи
        if not ttn.loading_batch:
            # Ищем партии приёмки с похожими данными
            loading_batches = BalloonsBatch.objects.filter(
                batch_type='l',
                truck=ttn.truck if hasattr(ttn, 'truck') else None,
                started_at__date=ttn.date.date() if hasattr(ttn, 'date') else None
            ).first()
            
            if loading_batches:
                ttn.loading_batch = loading_batches
                ttn.save(update_fields=['loading_batch'])
        
        # Восстанавливаем unloading_batch если есть соответствующие записи
        if not ttn.unloading_batch:
            # Ищем партии отгрузки с похожими данными
            unloading_batches = BalloonsBatch.objects.filter(
                batch_type='u',
                truck=ttn.truck if hasattr(ttn, 'truck') else None,
                started_at__date=ttn.date.date() if hasattr(ttn, 'date') else None
            ).first()
            
            if unloading_batches:
                ttn.unloading_batch = unloading_batches
                ttn.save(update_fields=['unloading_batch'])


def reverse_restore_balloon_batch_references(apps, schema_editor):
    """
    Обратная миграция - обнуляет все ссылки
    """
    BalloonTtn = apps.get_model('ttn', 'BalloonTtn')
    
    # Обнуляем все ссылки
    BalloonTtn.objects.all().update(
        loading_batch=None,
        unloading_batch=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0010_alter_balloonttn_loading_batch_and_more'),
        ('filling_station', '0079_delete_balloonsloadingbatch_and_more'),
    ]

    operations = [
        migrations.RunPython(
            restore_balloon_batch_references,
            reverse_restore_balloon_batch_references,
        ),
    ]
