# Generated by Django 5.2.4 on 2025-10-21 13:20

from django.db import migrations


def clear_balloon_batch_references_before_alter(apps, schema_editor):
    """
    Обнуляет все ссылки на партии баллонов перед изменением внешних ключей
    """
    BalloonTtn = apps.get_model('ttn', 'BalloonTtn')
    
    # Обнуляем все ссылки
    BalloonTtn.objects.all().update(
        loading_batch=None,
        unloading_batch=None
    )


def reverse_clear_balloon_batch_references_before_alter(apps, schema_editor):
    """
    Обратная миграция - ничего не делаем
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ttn', '0009_emailrecipient'),
    ]

    operations = [
        migrations.RunPython(
            clear_balloon_batch_references_before_alter,
            reverse_clear_balloon_batch_references_before_alter,
        ),
    ]
