# Generated by Django 5.2.7 on 2025-12-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselsettings',
            name='max_passport_weight_diff',
            field=models.FloatField(default=21.5, verbose_name='Максимальная разница в паспортных весах баллона'),
        ),
    ]
