# Generated by Django 5.2.4 on 2025-09-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselsettings',
            name='max_balloon_weight',
            field=models.FloatField(default=46.5, verbose_name='Максимальный вес баллона'),
        ),
        migrations.AddField(
            model_name='carouselsettings',
            name='min_balloon_weight',
            field=models.FloatField(default=17.8, verbose_name='Минимальный вес баллона'),
        ),
    ]
