# Generated by Django 5.2.4 on 2025-10-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_carouselsettings_max_balloon_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['-change_at'], 'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусель'},
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='change_time',
        ),
        migrations.AddField(
            model_name='carousel',
            name='change_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменений'),
        ),
    ]
