# Generated by Django 5.2.4 on 2026-09-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0007_carouselsettings_classify_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
