# Generated by Django 5.2.7 on 2025-12-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balloonsbatch',
            name='id_ttn',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID ТТН в Мириаде'),
        ),
    ]
