# Generated by Django 5.2.4 on 2025-12-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0002_balloonsbatch_id_ttn'),
        ('ttn', '0003_alter_miriadattn_options_remove_miriadattn_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balloonsbatch',
            name='amount_of_ttn',
        ),
        migrations.RemoveField(
            model_name='balloonsbatch',
            name='ttn',
        ),
        migrations.AlterField(
            model_name='balloonsbatch',
            name='id_ttn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ttn.miriadattn', verbose_name='ID ТТН'),
        ),
    ]
