# Generated by Django 5.2.7 on 2025-12-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0003_remove_balloonsbatch_amount_of_ttn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balloonsbatch',
            name='amount_of_sensor',
            field=models.IntegerField(default=0, verbose_name='Количество баллонов по датчику'),
        ),
        migrations.AddField(
            model_name='balloonsbatch',
            name='balloons_type',
            field=models.CharField(choices=[('e', 'Пустой'), ('f', 'Полный')], default='e', verbose_name='Пустой/полный'),
        ),
        migrations.AlterField(
            model_name='balloonsbatch',
            name='id_ttn',
            field=models.CharField(default='', max_length=20, verbose_name='ID ТТН'),
            preserve_default=False,
        ),
    ]
