# Generated by Django 5.2.7 on 2025-12-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0004_balloonsbatch_amount_of_sensor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balloonsbatch',
            name='id_ttn',
        ),
    ]
