# Generated by Django 5.2.7 on 2025-12-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0005_remove_balloonsbatch_id_ttn'),
    ]

    operations = [
        migrations.AddField(
            model_name='balloonsbatch',
            name='id_ttn',
            field=models.IntegerField(default=0, verbose_name='ID ТТН'),
            preserve_default=False,
        ),
    ]
