# Generated by Django 5.2.7 on 2025-12-18 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0006_balloonsbatch_id_ttn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balloonsbatch',
            old_name='id_ttn',
            new_name='ttn_id',
        ),
        migrations.AlterField(
            model_name='balloonsbatch',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailer', verbose_name='Прицеп'),
        ),
    ]
