# Generated by Django 5.2.4 on 2025-12-24 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0007_rename_id_ttn_balloonsbatch_ttn_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalsReaderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_empty', models.IntegerField(default=0, verbose_name='Всего пустых баллонов')),
                ('total_full', models.IntegerField(default=0, verbose_name='Всего полных баллонов')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Свод по складу',
                'verbose_name_plural': 'Свод по складу',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReaderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='Дата')),
                ('amount_of_rfid', models.IntegerField(default=0, verbose_name='Баллонов по RFID')),
                ('amount_of_sensor', models.IntegerField(default=0, verbose_name='Баллонов по сенсору')),
                ('change_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reader_number', to='filling_station.readersettings', verbose_name='Номер считывателя')),
            ],
            options={
                'verbose_name': 'Счетчики по ридерам за день',
                'verbose_name_plural': 'Счетчики по ридерам за день',
                'ordering': ['-day'],
            },
        ),
    ]
