# Generated by Django 5.2.4 on 2025-12-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0008_totalsreadercounter_dailyreadercounter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotalsReaderCounter',
            new_name='TotalReadersCounter',
        ),
        migrations.AlterField(
            model_name='dailyreadercounter',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_counters', to='filling_station.readersettings', verbose_name='Номер считывателя'),
        ),
    ]
