# Generated by Django 5.2.4 on 2025-12-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0009_rename_totalsreadercounter_totalreaderscounter_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyreadercounter',
            constraint=models.UniqueConstraint(fields=('number', 'day'), name='uniq_number_day'),
        ),
    ]
