# Generated by Django 5.2.4 on 2026-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0011_balloonsbatch_miriada_close_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='balloonsbatch',
            name='miriada_error_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст ошибки при неудачном закрытии ТТН'),
        ),
    ]
