# Generated by Django 5.2.4 on 2026-08-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0012_balloonsbatch_miriada_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='balloonsbatch',
            name='amount_of_ttn',
            field=models.IntegerField(default=0, verbose_name='Количество баллонов по электронной ТТН'),
        ),
        migrations.AddField(
            model_name='balloonsbatch',
            name='miriada_balloons_sent',
            field=models.BooleanField(default=False, verbose_name='Статусы баллонов отправлены в Мириаду'),
        ),
    ]
