# Generated by Django 5.2.4 on 2026-08-25 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0015_remove_balloonsbatch_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloonsbatch',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='filling_station.trailer', verbose_name='Прицеп'),
        ),
        migrations.AlterField(
            model_name='balloonsbatch',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filling_station.truck', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='balloonsbatch',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='truck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trailer', to='filling_station.truck', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='filling_station.trailertype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='filling_station.trucktype', verbose_name='Тип'),
        ),
    ]
