# Generated by Django 5.1.4 on 2025-03-02 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0051_alter_railwaytank_options_ttn_carrier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='railwaytank',
            name='registration_number_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото номера'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='change_date',
            field=models.DateField(auto_now=True, verbose_name='Дата изменений'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='change_time',
            field=models.TimeField(auto_now=True, verbose_name='Время изменений'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='filling_status',
            field=models.BooleanField(default=False, verbose_name='Готов к наполнению'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='update_passport_required',
            field=models.BooleanField(default=True, verbose_name='Требуется обновление паспорта'),
        ),
        migrations.AlterField(
            model_name='railwaybatch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='filling_status',
            field=models.BooleanField(default=False, verbose_name='Готов к наполнению'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='nfc_tag',
            field=models.CharField(max_length=30, verbose_name='Номер метки'),
        ),
        migrations.AlterField(
            model_name='trailertype',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип прицепа'),
        ),
        migrations.AlterField(
            model_name='trucktype',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип грузовика'),
        ),
    ]
