# Generated by Django 5.1.4 on 2025-03-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0052_railwaytank_registration_number_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwaytank',
            name='registration_number_img',
            field=models.ImageField(blank=True, null=True, upload_to='railway_tanks/', verbose_name='Фото номера'),
        ),
    ]
