# Generated by Django 5.1.4 on 2025-04-07 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0055_alter_railwayttn_options_alter_trailer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGasBatchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_source', models.CharField(choices=[('f', 'Расходомер'), ('s', 'Весы')], default='f', verbose_name='Источник веса для ТТН')),
            ],
            options={
                'verbose_name': 'Настройки автоколонки',
                'verbose_name_plural': 'Настройки автоколонки',
            },
        ),
        migrations.CreateModel(
            name='AutoTtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер ТТН')),
                ('contract', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('total_gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество газа')),
                ('gas_type', models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата формирования накладной')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tank_carrier', to='filling_station.carrier', verbose_name='Перевозчик')),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tank_consignee', to='filling_station.consignee', verbose_name='Грузополучатель')),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_tank_shipper', to='filling_station.shipper', verbose_name='Грузоотправитель')),
                ('source_gas_amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filling_station.autogasbatchsettings', verbose_name='Источник веса для ТТН')),
            ],
            options={
                'verbose_name': 'ТТН на автоцистерны',
                'verbose_name_plural': 'ТТН на автоцистерны',
                'ordering': ['-id', '-date'],
            },
        ),
    ]
