# Generated by Django 5.1.4 on 2025-04-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0056_autogasbatchsettings_autottn'),
    ]

    operations = [
        migrations.AddField(
            model_name='autottn',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_batch_for_ttn', to='filling_station.autogasbatch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='autottn',
            name='source_gas_amount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Источник веса для ТТН'),
        ),
    ]
