# Generated by Django 5.1.4 on 2025-04-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0057_autottn_batch_alter_autottn_source_gas_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='consignee',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='shipper',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код'),
        ),
    ]
