# Generated by Django 5.1.4 on 2025-04-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0060_alter_newttn_carrier_alter_autottn_carrier_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.AlterField(
            model_name='newttn',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер ТТН'),
        ),
        migrations.DeleteModel(
            name='CarouselSettings',
        ),
    ]
