# Generated by Django 5.1.4 on 2025-04-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0061_delete_carousel_alter_newttn_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autogasbatch',
            name='ttn',
        ),
        migrations.DeleteModel(
            name='TTN',
        ),
    ]
