# Generated by Django 5.1.4 on 2025-04-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0062_remove_autogasbatch_ttn_delete_ttn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewTTN',
            new_name='TTN',
        ),
    ]
