# Generated by Django 5.1.4 on 2025-05-01 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0063_rename_newttn_ttn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autottn',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_batch_for_ttn1', to='filling_station.autogasbatch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='railwayttn',
            name='railway_tank_list',
            field=models.ManyToManyField(blank=True, related_name='railway_tanks', to='filling_station.railwaytank', verbose_name='Список жд цистерн'),
        ),
        migrations.AlterField(
            model_name='ttn',
            name='loading_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttn_loading_old', to='filling_station.balloonsloadingbatch', verbose_name='Партия приёмки'),
        ),
        migrations.AlterField(
            model_name='ttn',
            name='unloading_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttn_unloading_old', to='filling_station.balloonsunloadingbatch', verbose_name='Партия отгрузки'),
        ),
    ]
