# Generated by Django 5.1.4 on 2025-05-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0064_alter_autottn_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttn',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='ttn',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='railwayttn',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='railwayttn',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='ttn',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='railwayttn',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='railwayttn',
            name='railway_tank_list',
        ),
        migrations.RemoveField(
            model_name='ttn',
            name='loading_batch',
        ),
        migrations.RemoveField(
            model_name='ttn',
            name='unloading_batch',
        ),
        migrations.DeleteModel(
            name='AutoTtn',
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
        migrations.DeleteModel(
            name='RailwayTtn',
        ),
        migrations.DeleteModel(
            name='TTN',
        ),
    ]
