# Generated by Django 5.1.4 on 2025-05-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0065_remove_ttn_carrier_remove_ttn_consignee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilePath',
        ),
    ]
