# Generated by Django 5.1.4 on 2025-05-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0067_alter_railwaybatch_user_alter_railwaytank_user'),
        ('ttn', '0003_filepath_alter_autottn_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railwaytank',
            name='user',
        ),
        migrations.DeleteModel(
            name='RailwayBatch',
        ),
        migrations.DeleteModel(
            name='RailwayTank',
        ),
    ]
