# Generated by Django 5.2.1 on 2025-07-30 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0069_alter_balloon_options_remove_balloon_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autogasbatch',
            options={'ordering': ['-begin_date', '-begin_time'], 'verbose_name': '_Автоколонка', 'verbose_name_plural': 'А_втоколонка'},
        ),
        migrations.AlterModelOptions(
            name='autogasbatchsettings',
            options={'verbose_name': '_Настройки автоколонки', 'verbose_name_plural': '_Настройки автоколонки'},
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='batch_type',
            field=models.CharField(choices=[('l', 'Приёмка'), ('u', 'Отгрузка')], default='u', max_length=10, verbose_name='_Тип партии'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='begin_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='_Дата начала приёмки'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='begin_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='_Время начала приёмки'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='_Дата окончания приёмки'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='_Время окончания приёмки'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='gas_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='__Количество газа (массомер)'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='gas_type',
            field=models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='_Тип газа'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='_В работе'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='scale_empty_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='_Вес пустого т/с (весы)'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='scale_full_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='_Вес полного т/с (весы)'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='trailer',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filling_set_trailer', to='filling_station.trailer', verbose_name='_Прицеп'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filling_set_Truck', to='filling_station.truck', verbose_name='_Автомобиль'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filling_set_User', to=settings.AUTH_USER_MODEL, verbose_name='_Пользователь'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='weight_gas_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='_Количество газа (весы)'),
        ),
        migrations.AlterField(
            model_name='autogasbatchsettings',
            name='weight_source',
            field=models.CharField(choices=[('f', 'Расходомер'), ('s', 'Весы')], default='f', verbose_name='_Источник веса для ТТН'),
        ),
    ]
