# Generated by Django 5.2.1 on 2025-07-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0070_alter_autogasbatch_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autogasbatch',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='autogasbatch',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='autogasbatch',
            name='user',
        ),
        migrations.DeleteModel(
            name='AutoGasBatchSettings',
        ),
        migrations.DeleteModel(
            name='AutoGasBatch',
        ),
    ]
