# Generated by Django 5.2.1 on 2025-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0071_remove_autogasbatch_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloonsloadingbatch',
            name='amount_of_12_liters',
            field=models.IntegerField(default=0, verbose_name='Количество 12л баллонов'),
        ),
        migrations.AlterField(
            model_name='balloonsloadingbatch',
            name='amount_of_27_liters',
            field=models.IntegerField(default=0, verbose_name='Количество 27л баллонов'),
        ),
        migrations.AlterField(
            model_name='balloonsloadingbatch',
            name='amount_of_50_liters',
            field=models.IntegerField(default=0, verbose_name='Количество 50л баллонов'),
        ),
        migrations.AlterField(
            model_name='balloonsloadingbatch',
            name='amount_of_5_liters',
            field=models.IntegerField(default=0, verbose_name='Количество 5л баллонов'),
        ),
        migrations.AlterField(
            model_name='balloonsloadingbatch',
            name='amount_of_rfid',
            field=models.IntegerField(default=0, verbose_name='Количество баллонов по rfid'),
        ),
        migrations.AlterField(
            model_name='balloonsloadingbatch',
            name='begin_date',
            field=models.DateField(auto_now_add=True, default='2025-06-10', verbose_name='Дата начала приёмки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balloonsloadingbatch',
            name='begin_time',
            field=models.TimeField(auto_now_add=True, default='14:30:00', verbose_name='Время начала приёмки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balloonsloadingbatch',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='В работе'),
        ),
        migrations.AlterField(
            model_name='balloonsunloadingbatch',
            name='amount_of_12_liters',
            field=models.IntegerField(default=0, verbose_name='Количество 12л баллонов'),
        ),
        migrations.AlterField(
            model_name='balloonsunloadingbatch',
            name='amount_of_27_liters',
            field=models.IntegerField(default=0, verbose_name='Количество 27л баллонов'),
        ),
        migrations.AlterField(
            model_name='balloonsunloadingbatch',
            name='amount_of_50_liters',
            field=models.IntegerField(default=0, verbose_name='Количество 50л баллонов'),
        ),
        migrations.AlterField(
            model_name='balloonsunloadingbatch',
            name='amount_of_5_liters',
            field=models.IntegerField(default=0, verbose_name='Количество 5л баллонов'),
        ),
        migrations.AlterField(
            model_name='balloonsunloadingbatch',
            name='amount_of_rfid',
            field=models.IntegerField(default=0, verbose_name='Количество баллонов по rfid'),
        ),
        migrations.AlterField(
            model_name='balloonsunloadingbatch',
            name='begin_date',
            field=models.DateField(auto_now_add=True, default='2025-06-10', verbose_name='Дата начала отгрузки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balloonsunloadingbatch',
            name='begin_time',
            field=models.TimeField(auto_now_add=True, default='14:30:00', verbose_name='Время начала отгрузки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balloonsunloadingbatch',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='В работе'),
        ),
    ]
