# Generated by Django 5.2.4 on 2025-08-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0072_alter_balloonsloadingbatch_amount_of_12_liters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={'ordering': ['-change_date'], 'verbose_name': 'Считыватель', 'verbose_name_plural': 'Считыватели'},
        ),
        migrations.RemoveField(
            model_name='reader',
            name='change_time',
        ),
        migrations.AlterField(
            model_name='reader',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменений'),
        ),
    ]
