# Generated by Django 5.2.4 on 2025-08-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0073_alter_reader_options_remove_reader_change_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderSettings',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер считывателя')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус')),
                ('ip', models.CharField(max_length=15, null=True, verbose_name='IP адрес')),
                ('port', models.IntegerField(default=10001, verbose_name='Порт')),
                ('function', models.CharField(choices=[('l', 'loading'), ('u', 'unloading'), ('p', 'pass')], default='p', verbose_name='Функция')),
            ],
            options={
                'verbose_name': 'Настройки считывателей',
                'verbose_name_plural': 'Настройки считывателей',
                'ordering': ['number'],
            },
        ),
        migrations.DeleteModel(
            name='BalloonAmount',
        ),
        migrations.AlterField(
            model_name='reader',
            name='nfc_tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер метки'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='is_on_station',
            field=models.BooleanField(default=False, verbose_name='Находится на станции'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='is_on_station',
            field=models.BooleanField(default=False, verbose_name='Находится на станции'),
        ),
    ]
