# Generated by Django 5.2.4 on 2025-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0074_readersettings_delete_balloonamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readersettings',
            name='need_cache',
            field=models.BooleanField(default=False, verbose_name='Добавлять в кеш'),
        ),
        migrations.AlterField(
            model_name='readersettings',
            name='function',
            field=models.CharField(choices=[('l', 'loading'), ('u', 'unloading'), ('p', None)], default='p', verbose_name='Функция'),
        ),
    ]
