# Generated by Django 5.2.4 on 2025-08-13 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0075_readersettings_need_cache_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reader_settings', to='filling_station.readersettings', verbose_name='Номер считывателя'),
        ),
    ]
