# Generated by Django 5.2.4 on 2025-08-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0076_alter_reader_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readersettings',
            name='function',
            field=models.CharField(choices=[('l', 'Приёмка'), ('u', 'Отгрузка'), ('p', 'Нет')], default='p', verbose_name='Функция'),
        ),
    ]
