# Generated by Django 5.2.4 on 2025-10-21 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0077_alter_readersettings_function'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balloonsloadingbatch',
            name='balloon_list',
        ),
        migrations.RemoveField(
            model_name='balloonsloadingbatch',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='balloonsloadingbatch',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='balloonsloadingbatch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='balloonsunloadingbatch',
            name='balloon_list',
        ),
        migrations.RemoveField(
            model_name='balloonsunloadingbatch',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='balloonsunloadingbatch',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='balloonsunloadingbatch',
            name='user',
        ),
        migrations.CreateModel(
            name='BalloonsBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('l', 'Приёмка'), ('u', 'Отгрузка')], default='l', verbose_name='Тип партии')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('reader_number', models.IntegerField(blank=True, null=True, verbose_name='Номер считывателя')),
                ('amount_of_rfid', models.IntegerField(default=0, verbose_name='Количество баллонов по rfid')),
                ('amount_of_5_liters', models.IntegerField(default=0, verbose_name='Количество 5л баллонов')),
                ('amount_of_12_liters', models.IntegerField(default=0, verbose_name='Количество 12л баллонов')),
                ('amount_of_27_liters', models.IntegerField(default=0, verbose_name='Количество 27л баллонов')),
                ('amount_of_50_liters', models.IntegerField(default=0, verbose_name='Количество 50л баллонов')),
                ('gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество принятого газа')),
                ('is_active', models.BooleanField(default=False, verbose_name='В работе')),
                ('ttn', models.CharField(default='', max_length=20, verbose_name='Номер ТТН')),
                ('amount_of_ttn', models.IntegerField(blank=True, null=True, verbose_name='Количество баллонов по ТТН')),
                ('balloon_list', models.ManyToManyField(blank=True, to='filling_station.balloon', verbose_name='Список баллонов')),
                ('trailer', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailer', verbose_name='Прицеп')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.truck', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Партия баллонов',
                'verbose_name_plural': 'Партии баллонов',
                'ordering': ['-started_at'],
            },
        ),
    ]
