# Generated by Django 5.2.4 on 2025-10-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0078_remove_balloonsloadingbatch_balloon_list_and_more'),
        ('ttn', '0010_alter_balloonttn_loading_batch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalloonsLoadingBatch',
        ),
        migrations.DeleteModel(
            name='BalloonsUnloadingBatch',
        ),
    ]
