# Generated by Django 5.2.4 on 2025-10-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0079_delete_balloonsloadingbatch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ['-is_on_station', '-entry_at'], 'verbose_name': 'Прицеп', 'verbose_name_plural': 'Прицепы'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['-is_on_station', '-entry_at'], 'verbose_name': 'Грузовик', 'verbose_name_plural': 'Грузовики'},
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='entry_time',
        ),
        migrations.AddField(
            model_name='trailer',
            name='departure_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выезда'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='entry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время въезда'),
        ),
        migrations.AddField(
            model_name='truck',
            name='departure_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выезда'),
        ),
        migrations.AddField(
            model_name='truck',
            name='entry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время въезда'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='empty_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес пустого т/с (по техпаспорту)'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='full_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес полного т/с (по техпаспорту)'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='max_gas_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальный объём перевозимого газа'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='max_mass_of_transported_gas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная масса перевозимого газа'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='max_weight_of_transported_cylinders',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная масса перевозимых баллонов'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='registration_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Регистрационный знак'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='empty_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес пустого т/с (по техпаспорту)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='full_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес полного т/с (по техпаспорту)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='max_gas_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальный объём перевозимого газа'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='max_mass_of_transported_gas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная масса перевозимого газа'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='max_weight_of_transported_cylinders',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная масса перевозимых баллонов'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='registration_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Регистрационный знак'),
        ),
    ]
