# Generated by Django 5.1.4 on 2025-04-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=10, unique=True, verbose_name='Номер версии')),
                ('apk_file', models.FileField(upload_to='apk/', verbose_name='APK файл')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Версия мобильного приложения',
                'verbose_name_plural': 'Версии мобильного приложения',
                'ordering': ['-update_date'],
            },
        ),
    ]
