# Generated by Django 5.1.4 on 2025-05-13 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, verbose_name='Номер ж/д цистерны')),
                ('empty_weight', models.FloatField(blank=True, null=True, verbose_name='Вес пустой цистерны')),
                ('full_weight', models.FloatField(blank=True, null=True, verbose_name='Вес полной цистерны')),
                ('gas_weight', models.FloatField(blank=True, null=True, verbose_name='Масса перевозимого газа')),
                ('gas_type', models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа')),
                ('is_on_station', models.BooleanField(blank=True, null=True, verbose_name='Находится на станции')),
                ('railway_ttn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ж/д накладной')),
                ('netto_weight_ttn', models.FloatField(blank=True, null=True, verbose_name='Вес НЕТТО ж/д цистерны по накладной')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Дата въезда')),
                ('entry_time', models.TimeField(blank=True, null=True, verbose_name='Время въезда')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата выезда')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Время выезда')),
                ('registration_number_img', models.ImageField(blank=True, null=True, upload_to='railway_tanks/', verbose_name='Фото номера')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ж/д цистерна',
                'verbose_name_plural': 'Ж/д цистерны',
                'ordering': ['-is_on_station', '-entry_date', '-entry_time', '-departure_date', '-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='RailwayBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала приёмки')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания приёмки')),
                ('gas_amount_spbt', models.FloatField(blank=True, null=True, verbose_name='Количество принятого СПБТ газа')),
                ('gas_amount_pba', models.FloatField(blank=True, null=True, verbose_name='Количество принятого ПБА газа')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='В работе')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('railway_tank_list', models.ManyToManyField(blank=True, to='railway_service.railwaytank', verbose_name='Список жд цистерн')),
            ],
            options={
                'verbose_name': 'Партия приёмки жд цистерн',
                'verbose_name_plural': 'Партии приёмки жд цистерн',
                'ordering': ['-begin_date'],
            },
        ),
    ]
