# Generated by Django 5.2.7 on 2025-10-26 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.IntegerField(unique=True, verbose_name='Номер ж/д цистерны')),
                ('gas_type', models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа')),
                ('is_on_station', models.BooleanField(default=False, verbose_name='Находится на станции')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ж/д цистерна',
                'verbose_name_plural': 'Ж/д цистерны',
                'ordering': ['-is_on_station'],
            },
        ),
        migrations.CreateModel(
            name='RailwayBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала приёмки')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания приёмки')),
                ('gas_amount_spbt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Количество принятого СПБТ газа')),
                ('gas_amount_pba', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Количество принятого ПБА газа')),
                ('is_active', models.BooleanField(default=False, verbose_name='В работе')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('railway_tank_list', models.ManyToManyField(blank=True, to='railway_service.railwaytank', verbose_name='Список жд цистерн')),
            ],
            options={
                'verbose_name': 'Партия приёмки жд цистерн',
                'verbose_name_plural': 'Партии приёмки жд цистерн',
                'ordering': ['-begin_date'],
            },
        ),
        migrations.CreateModel(
            name='RailwayTankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата въезда')),
                ('departure_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выезда')),
                ('full_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Вес полной цистерны')),
                ('empty_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Вес пустой цистерны')),
                ('gas_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Поставлено газа')),
                ('railway_ttn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ж/д накладной')),
                ('netto_weight_ttn', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Вес НЕТТО ж/д цистерны по накладной')),
                ('arrival_img', models.ImageField(blank=True, null=True, upload_to='railway_tanks/', verbose_name='Фото номера при въезде')),
                ('departure_img', models.ImageField(blank=True, null=True, upload_to='railway_tanks/', verbose_name='Фото номера при выезде')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_history', to='railway_service.railwaytank', verbose_name='Цистерна')),
            ],
            options={
                'verbose_name': 'История цистерны',
                'verbose_name_plural': 'Истории цистерн',
                'ordering': ['-arrival_at'],
            },
        ),
    ]
