# Generated by Django 5.2.7 on 2025-12-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railwaytank',
            name='gas_type',
        ),
        migrations.AddField(
            model_name='railwaytankhistory',
            name='gas_type',
            field=models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа'),
        ),
    ]
