# Generated by Django 5.2.4 on 2025-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='railwaytank',
            options={'ordering': ['-is_on_station', '-entry_date', '-departure_date'], 'verbose_name': 'Ж/д цистерна', 'verbose_name_plural': 'Ж/д цистерны'},
        ),
        migrations.RemoveField(
            model_name='railwaytank',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='railwaytank',
            name='entry_time',
        ),
        migrations.AlterField(
            model_name='railwaytank',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='railwaytank',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата въезда'),
        ),
    ]
