# Generated by Django 5.2.4 on 2025-09-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_service', '0002_alter_railwaytank_options_and_more'),
    ]

    operations = [
        # Добавляем новое поле registration_number_int
        migrations.AddField(
            model_name='railwaytank',
            name='registration_number_int',
            field=models.IntegerField(null=True, unique=True, verbose_name='Номер ж/д цистерны (int)'),
        ),
    ]
