# Generated by Django 5.2.4 on 2026-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_service', '0002_remove_railwaytank_gas_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwaytankhistory',
            name='gas_type',
            field=models.CharField(choices=[('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='СПБТ', max_length=10, verbose_name='Тип газа'),
        ),
    ]
