# Generated by Django 5.2.4 on 2025-09-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_service', '0004_migrate_registration_numbers'),
    ]

    operations = [
        # Удаляем старое поле registration_number
        migrations.RemoveField(
            model_name='railwaytank',
            name='registration_number',
        ),
        # Переименовываем registration_number_int в registration_number
        migrations.RenameField(
            model_name='railwaytank',
            old_name='registration_number_int',
            new_name='registration_number',
        ),
        # Делаем поле обязательным и уникальным
        migrations.AlterField(
            model_name='railwaytank',
            name='registration_number',
            field=models.IntegerField(unique=True, verbose_name='Номер ж/д цистерны'),
        ),
    ]
