# Generated by Django 5.2.4 on 2025-09-16 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_service', '0005_replace_registration_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='railwaytank',
            options={'ordering': ['-is_on_station'], 'verbose_name': 'Ж/д цистерна', 'verbose_name_plural': 'Ж/д цистерны'},
        ),
        migrations.RemoveField(
            model_name='railwaytank',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='railwaytank',
            name='empty_weight',
        ),
        migrations.RemoveField(
            model_name='railwaytank',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='railwaytank',
            name='full_weight',
        ),
        migrations.RemoveField(
            model_name='railwaytank',
            name='gas_weight',
        ),
        migrations.RemoveField(
            model_name='railwaytank',
            name='netto_weight_ttn',
        ),
        migrations.RemoveField(
            model_name='railwaytank',
            name='railway_ttn',
        ),
        migrations.AlterField(
            model_name='railwaybatch',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='В работе'),
        ),
        migrations.AlterField(
            model_name='railwaytank',
            name='is_on_station',
            field=models.BooleanField(default=False, verbose_name='Находится на станции'),
        ),
        migrations.AlterField(
            model_name='railwaytank',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='RailwayTankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата въезда')),
                ('departure_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выезда')),
                ('full_weight', models.FloatField(blank=True, null=True, verbose_name='Вес полной цистерны')),
                ('empty_weight', models.FloatField(blank=True, null=True, verbose_name='Вес пустой цистерны')),
                ('gas_weight', models.FloatField(blank=True, null=True, verbose_name='Поставлено газа')),
                ('railway_ttn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ж/д накладной')),
                ('netto_weight_ttn', models.FloatField(blank=True, null=True, verbose_name='Вес НЕТТО ж/д цистерны по накладной')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_history', to='railway_service.railwaytank', verbose_name='Цистерна')),
            ],
            options={
                'verbose_name': 'История цистерны',
                'verbose_name_plural': 'Истории цистерн',
                'ordering': ['-arrival_at', '-departure_at'],
            },
        ),
    ]
