# Generated by Django 5.2.4 on 2025-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_service', '0006_add_railway_tank_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railwaytank',
            name='registration_number_img',
        ),
        migrations.AddField(
            model_name='railwaytankhistory',
            name='arrival_img',
            field=models.ImageField(blank=True, null=True, upload_to='railway_tanks/', verbose_name='Фото номера при въезде'),
        ),
        migrations.AddField(
            model_name='railwaytankhistory',
            name='departure_img',
            field=models.ImageField(blank=True, null=True, upload_to='railway_tanks/', verbose_name='Фото номера при выезде'),
        ),
    ]
