# Generated by Django 5.2.4 on 2025-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_service', '0007_remove_railwaytank_registration_number_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwaybatch',
            name='gas_amount_pba',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество принятого ПБА газа'),
        ),
        migrations.AlterField(
            model_name='railwaybatch',
            name='gas_amount_spbt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество принятого СПБТ газа'),
        ),
        migrations.AlterField(
            model_name='railwaytankhistory',
            name='empty_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вес пустой цистерны'),
        ),
        migrations.AlterField(
            model_name='railwaytankhistory',
            name='full_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вес полной цистерны'),
        ),
        migrations.AlterField(
            model_name='railwaytankhistory',
            name='gas_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Поставлено газа'),
        ),
        migrations.AlterField(
            model_name='railwaytankhistory',
            name='netto_weight_ttn',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вес НЕТТО ж/д цистерны по накладной'),
        ),
    ]
