# Generated by Django 5.2.4 on 2025-10-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_service', '0008_alter_railwaybatch_gas_amount_pba_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='railwaytankhistory',
            options={'ordering': ['-arrival_at'], 'verbose_name': 'История цистерны', 'verbose_name_plural': 'Истории цистерн'},
        ),
        migrations.AlterField(
            model_name='railwaytankhistory',
            name='empty_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Вес пустой цистерны'),
        ),
        migrations.AlterField(
            model_name='railwaytankhistory',
            name='full_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Вес полной цистерны'),
        ),
        migrations.AlterField(
            model_name='railwaytankhistory',
            name='gas_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Поставлено газа'),
        ),
        migrations.AlterField(
            model_name='railwaytankhistory',
            name='netto_weight_ttn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Вес НЕТТО ж/д цистерны по накладной'),
        ),
    ]
