# Generated by Django 5.2.4 on 2025-10-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_service', '0009_alter_railwaytankhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwaybatch',
            name='gas_amount_pba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Количество принятого ПБА газа'),
        ),
        migrations.AlterField(
            model_name='railwaybatch',
            name='gas_amount_spbt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Количество принятого СПБТ газа'),
        ),
    ]
