version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  adminer:
      image: adminer
      container_name: adminer
      restart: always
      ports:
        - 8080:8080

  django_backend:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}

  rfid:
    build: ../rfid app
    container_name: rfid
    restart: always
    ports:
      - 8001:8001
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}

volumes:
  postgres_data:

networks:
    app_network:
        name: 'app_network'