# Generated by Django 5.2.1 on 2025-07-30 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filling_station', '0070_alter_autogasbatch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGasBatchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_source', models.CharField(choices=[('f', 'Расходомер'), ('s', 'Весы')], default='f', verbose_name='Источник веса для ТТН')),
            ],
            options={
                'verbose_name': 'Настройки автоколонки',
                'verbose_name_plural': 'Настройки автоколонки',
            },
        ),
        migrations.CreateModel(
            name='AutoGasBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('l', 'Приёмка'), ('u', 'Отгрузка')], default='u', max_length=10, verbose_name='Тип партии')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='Дата начала приёмки')),
                ('begin_time', models.TimeField(blank=True, null=True, verbose_name='Время начала приёмки')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания приёмки')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания приёмки')),
                ('gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество газа (массомер)')),
                ('gas_type', models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа')),
                ('scale_empty_weight', models.FloatField(blank=True, null=True, verbose_name='Вес пустого т/с (весы)')),
                ('scale_full_weight', models.FloatField(blank=True, null=True, verbose_name='Вес полного т/с (весы)')),
                ('weight_gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество газа (весы)')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='В работе')),
                ('trailer', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailer', verbose_name='Прицеп')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.truck', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Автоколонка',
                'verbose_name_plural': 'Автоколонка',
                'ordering': ['-begin_date', '-begin_time'],
            },
        ),
    ]
