# Generated by Django 5.2.7 on 2025-10-26 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filling_station', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGasBatchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_source', models.CharField(choices=[('f', 'Расходомер'), ('s', 'Весы')], default='f', verbose_name='Источник веса для ТТН')),
            ],
            options={
                'verbose_name': 'Настройки автоколонки',
                'verbose_name_plural': 'Настройки автоколонки',
            },
        ),
        migrations.CreateModel(
            name='AutoGasBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('l', 'Приёмка'), ('u', 'Отгрузка')], default='u', verbose_name='Тип партии')),
                ('begin_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('gas_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Количество газа (массомер)')),
                ('gas_type', models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', verbose_name='Тип газа')),
                ('scale_empty_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Вес пустого т/с (весы)')),
                ('scale_full_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Вес полного т/с (весы)')),
                ('weight_gas_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Количество газа (весы)')),
                ('is_active', models.BooleanField(default=False, verbose_name='В работе')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailer', verbose_name='Прицеп')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.truck', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Автоколонка',
                'verbose_name_plural': 'Автоколонка',
                'ordering': ['-is_active', '-begin_at'],
            },
        ),
    ]
