# Generated by Django 5.2.1 on 2025-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autogas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogasbatch',
            name='begin_date',
            field=models.DateField(auto_now_add=True, default='2025-07-30', verbose_name='Дата начала приёмки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='begin_time',
            field=models.TimeField(auto_now_add=True, default='14:30:00', verbose_name='Время начала приёмки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='В работе'),
        ),
    ]
