# Generated by Django 5.2.4 on 2026-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autogas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogasbatch',
            name='gas_type',
            field=models.CharField(choices=[('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='СПБТ', verbose_name='Тип газа'),
        ),
    ]
