# Generated by Django 5.2.4 on 2025-10-18 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autogas', '0002_alter_autogasbatch_begin_date_and_more'),
        ('filling_station', '0077_alter_readersettings_function'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autogasbatch',
            options={'ordering': ['-begin_at'], 'verbose_name': 'Автоколонка', 'verbose_name_plural': 'Автоколонка'},
        ),
        migrations.RemoveField(
            model_name='autogasbatch',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='autogasbatch',
            name='begin_time',
        ),
        migrations.RemoveField(
            model_name='autogasbatch',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='autogasbatch',
            name='end_time',
        ),
        migrations.AddField(
            model_name='autogasbatch',
            name='begin_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-18 22:00', verbose_name='Дата и время начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autogasbatch',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='batch_type',
            field=models.CharField(choices=[('l', 'Приёмка'), ('u', 'Отгрузка')], default='u', verbose_name='Тип партии'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='gas_type',
            field=models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', verbose_name='Тип газа'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailer', verbose_name='Прицеп'),
        ),
    ]
