# Generated by Django 5.2.4 on 2026-08-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def deactivate_extra_active_batches(apps, schema_editor):
    AutoGasBatch = apps.get_model('autogas', 'AutoGasBatch')
    keep_id = (
        AutoGasBatch.objects.filter(is_active=True)
        .order_by('-begin_at', '-pk')
        .values_list('pk', flat=True)
        .first()
    )
    if keep_id is None:
        return
    (
        AutoGasBatch.objects.filter(is_active=True)
        .exclude(pk=keep_id)
        .update(is_active=False)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('autogas', '0002_alter_autogasbatch_gas_type'),
        ('filling_station', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            deactivate_extra_active_batches,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='trailer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='filling_station.trailer',
                verbose_name='Прицеп',
            ),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='truck',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='filling_station.truck',
                verbose_name='Автомобиль',
            ),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='user',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AddConstraint(
            model_name='autogasbatch',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)),
                fields=('is_active',),
                name='uniq_one_active_autogas_batch',
            ),
        ),
    ]
