# Generated by Django 5.2.4 on 2025-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autogas', '0003_alter_autogasbatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogasbatch',
            name='gas_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество газа (массомер)'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='scale_empty_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вес пустого т/с (весы)'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='scale_full_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вес полного т/с (весы)'),
        ),
        migrations.AlterField(
            model_name='autogasbatch',
            name='weight_gas_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество газа (весы)'),
        ),
    ]
