# Generated by Django 5.2.4 on 2025-10-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autogas', '0005_alter_autogasbatch_gas_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autogasbatch',
            options={'ordering': ['-is_active', '-begin_at'], 'verbose_name': 'Автоколонка', 'verbose_name_plural': 'Автоколонка'},
        ),
    ]
